
###
GET http://localhost:8080/customer

###
GET http://localhost:8080/customer/1

###
GET http://localhost:8080/customer/6

###
GET http://localhost:8080/pizza

###
GET http://localhost:8080/order

###
GET http://localhost:8080/order/paid
