export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASKET_ROUTE = '/basket'
export const MENU_ROUTE = '/'
export const PIZZA_ROUTE = '/pizza'
